-- [gold]
-- Gives sides gold.
-- amount: the amount of gold to give.
-- side: (default=1) the number of the side to give the gold to. Can be a comma-separated list of sides. note: Default side=1 for empty side= is deprecated.
-- StandardSideFilter tags and keys; default for empty side= is all sides, as usual in a SSF. 
